/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumextremep;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author Linda
 */
public class CreateBlogg extends javax.swing.JFrame {

    /**
     * Creates new form CreateBlogg
     */
    private String anvID;
    File filnamn;        
    String bild;
    String filpath;
    String sokvag;
    public CreateBlogg(String anvandarID) {
        initComponents();
        setLocationRelativeTo(null);
        fyllBloggar(); 
        fyllSubkategori();
        anvID = anvandarID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFTitle = new javax.swing.JTextField();
        spBlogFlow = new javax.swing.JScrollPane();
        TaCreateBlog = new javax.swing.JTextArea();
        cbBlog = new javax.swing.JComboBox<>();
        lbl_fil = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        CbCategory = new javax.swing.JComboBox<>();
        LbCreateCategory = new javax.swing.JLabel();
        TfNewCategory = new javax.swing.JTextField();
        BtNewCategory = new javax.swing.JButton();
        BtAddFile = new javax.swing.JButton();
        BtCreateBlog = new javax.swing.JButton();
        lblRubrik = new java.awt.Label();
        lblBild = new javax.swing.JLabel();
        btn_Bild = new javax.swing.JButton();
        lblBakgrundVit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1227, 774));
        getContentPane().setLayout(null);

        TFTitle.setText("Titel");
        TFTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFTitleFocusGained(evt);
            }
        });
        getContentPane().add(TFTitle);
        TFTitle.setBounds(80, 120, 220, 30);

        TaCreateBlog.setColumns(20);
        TaCreateBlog.setRows(5);
        spBlogFlow.setViewportView(TaCreateBlog);

        getContentPane().add(spBlogFlow);
        spBlogFlow.setBounds(80, 160, 680, 180);

        cbBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBlogActionPerformed(evt);
            }
        });
        getContentPane().add(cbBlog);
        cbBlog.setBounds(780, 190, 130, 30);

        lbl_fil.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lbl_fil);
        lbl_fil.setBounds(780, 450, 70, 20);

        BtnBack.setText("Tillbaka ");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBack);
        BtnBack.setBounds(843, 20, 130, 40);

        getContentPane().add(CbCategory);
        CbCategory.setBounds(780, 250, 130, 30);

        LbCreateCategory.setText("Skapa ny kategori");
        getContentPane().add(LbCreateCategory);
        LbCreateCategory.setBounds(780, 310, 110, 20);
        getContentPane().add(TfNewCategory);
        TfNewCategory.setBounds(780, 340, 130, 30);

        BtNewCategory.setText("Lägg till kategori");
        BtNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNewCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(BtNewCategory);
        BtNewCategory.setBounds(780, 390, 130, 20);

        BtAddFile.setText("Bifoga fil");
        BtAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddFileActionPerformed(evt);
            }
        });
        getContentPane().add(BtAddFile);
        BtAddFile.setBounds(779, 420, 130, 32);

        BtCreateBlog.setText("Skapa blogginlägg");
        BtCreateBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCreateBlogActionPerformed(evt);
            }
        });
        getContentPane().add(BtCreateBlog);
        BtCreateBlog.setBounds(780, 510, 134, 40);

        lblRubrik.setAlignment(java.awt.Label.CENTER);
        lblRubrik.setBackground(new java.awt.Color(255, 255, 255));
        lblRubrik.setFont(new java.awt.Font("Impact", 0, 52)); // NOI18N
        lblRubrik.setText("Informatikblogg");
        getContentPane().add(lblRubrik);
        lblRubrik.setBounds(260, 0, 480, 120);
        getContentPane().add(lblBild);
        lblBild.setBounds(80, 350, 680, 240);

        btn_Bild.setText("Bild");
        btn_Bild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BildActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Bild);
        btn_Bild.setBounds(780, 480, 110, 32);

        lblBakgrundVit.setBackground(java.awt.Color.white);
        lblBakgrundVit.setForeground(new java.awt.Color(255, 255, 255));
        lblBakgrundVit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumextremep/Namnlös.jpg"))); // NOI18N
        lblBakgrundVit.setText("jLabel1");
        getContentPane().add(lblBakgrundVit);
        lblBakgrundVit.setBounds(0, -10, 1000, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNewCategoryActionPerformed
                     
        try {
       
        String blogType = cbBlog.getSelectedItem().toString();
        String subC = TfNewCategory.getText(); 
       
      
        String CbBlog = "SELECT B_ID FROM BLOGG WHERE BLOGGNAMN = '"+ blogType +"'";
        CbBlog = Databas.getDatabas().fetchSingle(CbBlog);
        String userC = "SELECT A_ID FROM ANVANDARE WHERE ANVNAMN = '" + anvID + "'";
        userC = Databas.getDatabas().fetchSingle(userC);
        String SkID = Databas.getDatabas().getAutoIncrement("SUBKATEGORI" , "SK_ID");
        
        String sql = "INSERT INTO SUBKATEGORI values ('" + SkID +  "', '" +subC+ "' ,  "+CbBlog+", " + userC + ")";
        Databas.getDatabas().insert(sql);
                
        JOptionPane.showMessageDialog(null, "Den nya kategorin " + subC + " har lagts till");
        
         try
        {
        CbCategory.removeAllItems();
        fyllSubkategori();
        }
        catch(Exception e){
            System.out.println(e);
        }
        
      } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel: " + ex);
            }
      
    }//GEN-LAST:event_BtNewCategoryActionPerformed

    private void BtCreateBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCreateBlogActionPerformed
     
        
        try {
        String blogText = TaCreateBlog.getText();
        String blogType = cbBlog.getSelectedItem().toString();
        String user = anvID;
        String sub = CbCategory.getSelectedItem().toString();
        String titel = TFTitle.getText();
        
        
 
      
        String CbBlog = "SELECT B_ID FROM BLOGG WHERE BLOGGNAMN = '"+ blogType +"'";
        CbBlog = Databas.getDatabas().fetchSingle(CbBlog);
        String subC = "SELECT SK_ID FROM SUBKATEGORI WHERE SUBKATEGORI.NAMN = '" + sub + "'";
        subC = Databas.getDatabas().fetchSingle(subC);
        String userC = "SELECT A_ID FROM ANVANDARE WHERE A_ID = '" + user + "'";
        userC = Databas.getDatabas().fetchSingle(userC);
        String BiID = Databas.getDatabas().getAutoIncrement("BLOGGINLAGG" , "BI_ID");
        
        FileInputStream stream = new FileInputStream(filpath);
        FileOutputStream to = new FileOutputStream(sokvag + "//" +  bild);
                         
        byte [] buffer = new byte[81920];
        int byteRead;
        while((byteRead = stream.read(buffer)) != -1) {
        to.write(buffer,0,byteRead);
        }                
        
        String filen = lbl_fil.getText();
        
        if(filen == null){
            filen = "";
        }
        
        String sql = "INSERT INTO BLOGGINLAGG values (" + BiID +  ", '" + titel + "' , '" + blogText + "', '" + filen + "' , "+ userC +", "+ subC +" ," + CbBlog + ", '" + hamtaDatum() + "' , '" +bild+"')";
        Databas.getDatabas().insert(sql);
                
        JOptionPane.showMessageDialog(null, "Blogginlägget har skapats");
             
        } catch (FileNotFoundException ex) 
        {
            JOptionPane.showMessageDialog(null, "Välj en fil att visa" +ex.getMessage());   
        } 
        catch (IOException ex) 
        { 
            JOptionPane.showMessageDialog(null, "Välj en fil att visa");   
        }
        catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel: " + ex);
        }
      
    }//GEN-LAST:event_BtCreateBlogActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
       new InloggadSida(anvID).setVisible(true);
       dispose();
       
    }//GEN-LAST:event_BtnBackActionPerformed

    private void cbBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBlogActionPerformed
       try
        {
        CbCategory.removeAllItems();
        fyllSubkategori();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cbBlogActionPerformed

    private void TFTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFTitleFocusGained
        TFTitle.setText("");
    }//GEN-LAST:event_TFTitleFocusGained

    private void btn_BildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BildActionPerformed
        JFileChooser jfc = new JFileChooser(); 
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            String bildVag = jfc.getSelectedFile().getAbsolutePath();
            ImageIcon bilden = new ImageIcon(new ImageIcon(bildVag).getImage().getScaledInstance(680, 240, Image.SCALE_DEFAULT));
            lblBild.setIcon(bilden);
            
            File mappen = new File("bilder");
            sokvag = mappen.getAbsolutePath();
            filnamn = jfc.getSelectedFile();
            bild = jfc.getName(filnamn);
            filpath = filnamn.getAbsolutePath();
        } 
    }//GEN-LAST:event_btn_BildActionPerformed

    private void BtAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddFileActionPerformed
        oppnaChooser();
    }//GEN-LAST:event_BtAddFileActionPerformed

    
    public String hamtaDatum()
    {
        Date tobias = java.util.Calendar.getInstance().getTime();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dFormat.format(tobias);
    }
    
    public String oppnaChooser()
    {
        String stringfil = "";
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(CreateBlogg.this);
    
        if(Desktop.isDesktopSupported())
        {
                 File mappen = new File("src\\scrumextremep\\resources");
                 String mappensPath = mappen.getAbsolutePath();
            
                 File filnamnet = fc.getSelectedFile();
                 String filpathen = filnamnet.getAbsolutePath();
        
                  File filen = fc.getSelectedFile();
                 stringfil = filen.getName();
         try
         {
                    FileInputStream stream = new FileInputStream(filpathen);
                    FileOutputStream to = new FileOutputStream(mappensPath + "//" +  stringfil);
                         
                            byte [] buffer = new byte[24576000];
                            int byteRead;
                            while((byteRead = stream.read(buffer)) != -1) {
                            to.write(buffer,0,byteRead);
                            System.out.println(mappensPath + stringfil);
                            lbl_fil.setText(stringfil);
         return stringfil;
            }
            }       
         catch (FileNotFoundException ex) 
         {
                Logger.getLogger(CreateBlogg.class.getName()).log(Level.SEVERE, null, ex);
            } 
         catch (IOException ex) 
         {
                Logger.getLogger(CreateBlogg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return stringfil;
    }
  


    private void fyllBloggar()
    {
        try{
        String fyll = "SELECT BLOGGNAMN FROM BLOGG";
        ArrayList<HashMap<String, String>> bloggarna = Databas.getDatabas().fetchRows(fyll);
        for (int i = 0; i < bloggarna.size(); i++){
            cbBlog.addItem(bloggarna.get(i).get("BLOGGNAMN"));
                                                  }
           }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void fyllSubkategori()
    {
        try{
            String bloggnamn = cbBlog.getSelectedItem().toString();
        String fyll = "SELECT NAMN FROM SUBKATEGORI WHERE B_ID = (SELECT B_ID FROM BLOGG WHERE BLOGGNAMN = '" + bloggnamn + "')";
        ArrayList<HashMap<String, String>> bloggarna = Databas.getDatabas().fetchRows(fyll);
        if(bloggarna != null){
        for (int i = 0; i < bloggarna.size(); i++)
        {
            CbCategory.addItem(bloggarna.get(i).get("NAMN"));
        }
        }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddFile;
    private javax.swing.JButton BtCreateBlog;
    private javax.swing.JButton BtNewCategory;
    private javax.swing.JButton BtnBack;
    private javax.swing.JComboBox<String> CbCategory;
    private javax.swing.JLabel LbCreateCategory;
    private javax.swing.JTextField TFTitle;
    private javax.swing.JTextArea TaCreateBlog;
    private javax.swing.JTextField TfNewCategory;
    private javax.swing.JButton btn_Bild;
    private javax.swing.JComboBox<String> cbBlog;
    private javax.swing.JLabel lblBakgrundVit;
    private javax.swing.JLabel lblBild;
    private java.awt.Label lblRubrik;
    private javax.swing.JLabel lbl_fil;
    private javax.swing.JScrollPane spBlogFlow;
    // End of variables declaration//GEN-END:variables
}
