/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumextremep;

import javax.swing.JOptionPane;

/**
 *
 * @author elin-
 */
public class Laggtill extends javax.swing.JFrame {

    private boolean chbAdminChanged = false;
    private String anvID;
    /**
     * Creates new form Laggtill
     */
    public Laggtill(String anvandarID) {
        initComponents();
        anvID = anvandarID;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_fornamn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_efternamn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_anvnamn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_losenord = new javax.swing.JTextField();
        savenew = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        chbAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Lägg till ny profil");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Förnamn");

        txt_fornamn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Efternamn");

        txt_efternamn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Användarnamn");

        txt_anvnamn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-mail");

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Lösenord");

        txt_losenord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        savenew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        savenew.setText("Spara");
        savenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savenewActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        chbAdmin.setText("Administratör");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savenew, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(txt_fornamn)
                            .addComponent(jLabel3)
                            .addComponent(txt_efternamn)
                            .addComponent(txt_anvnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTillbaka)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_losenord, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(chbAdmin))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_losenord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_efternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_anvnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbAdmin))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savenew, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savenewActionPerformed
       if(Validering.tomtTextfalt(txt_fornamn) && Validering.valideraNamn(txt_fornamn)
               && Validering.tomtTextfalt(txt_efternamn) && Validering.valideraNamn(txt_efternamn)
               && Validering.tomtTextfalt(txt_email) && Validering.giltigMail(txt_email) && Validering.mailUnik(txt_email)
               && Validering.tomtTextfalt(txt_losenord) && Validering.valideraLosenLangd(txt_losenord)
               && Validering.tomtTextfalt(txt_anvnamn))
           
       { 
        
        
        addUser();
        JOptionPane.showMessageDialog(null, "Användare skapad!");
       }
    }//GEN-LAST:event_savenewActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminAnd(anvID).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void addUser() {
        String forn = txt_fornamn.getText();
        String lastn = txt_efternamn.getText();
        String usern = txt_anvnamn.getText();
        String mail = txt_email.getText();
        String password = txt_losenord.getText();
        if (chbAdmin.isSelected()) {
            try {
                String nextID = Databas.getDatabas().getAutoIncrement("ANVANDARE", "A_ID");
                Databas.getDatabas().insert("INSERT INTO ANVANDARE VALUES\n"+
                                            "("+ nextID +",'" + forn + "', '" + lastn + "', '" + usern + "',\n"+
                                            "'" + password + "', 'T', '" + mail + "');");
           
        } catch (Exception e) {
            System.out.println(e.getMessage());         
        } 
        } else {
            try {
                String nextID = Databas.getDatabas().getAutoIncrement("ANVANDARE", "A_ID");
                Databas.getDatabas().insert("INSERT INTO ANVANDARE VALUES (" + nextID + ", '" + forn + "', '" + lastn + "', '" + usern + "', '" + password + "', 'F', '" + mail + "');");
            } catch (Exception e) {
                System.out.println(e.getMessage()); 
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JCheckBox chbAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton savenew;
    private javax.swing.JTextField txt_anvnamn;
    private javax.swing.JTextField txt_efternamn;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fornamn;
    private javax.swing.JTextField txt_losenord;
    // End of variables declaration//GEN-END:variables
}
