/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumextremep;

import javax.swing.JOptionPane;

/**
 *
 * @author Timmy
 */
public class Motesforslag extends javax.swing.JFrame {
    
    private String anvID;

    /**
     * Creates new form Motesforslag
     */
    public Motesforslag(String anvandarID) {
        initComponents();
        anvID = anvandarID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMeetingname = new javax.swing.JLabel();
        lblSuggestion1 = new javax.swing.JLabel();
        lblSuggestion2 = new javax.swing.JLabel();
        lblSuggestion3el4 = new javax.swing.JLabel();
        lblSuggestion4 = new javax.swing.JLabel();
        lblMeetingDescrip = new javax.swing.JLabel();
        tfMeetingname = new javax.swing.JTextField();
        dcSuggestion1 = new com.toedter.calendar.JDateChooser();
        dcSuggestion2 = new com.toedter.calendar.JDateChooser();
        dcSuggestion3 = new com.toedter.calendar.JDateChooser();
        dcSuggestion4 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMeetingDescrip = new javax.swing.JTextArea();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMeetingname.setText("Name for Meeting");

        lblSuggestion1.setText("Suggestion 1");

        lblSuggestion2.setText("Suggestion 2");

        lblSuggestion3el4.setText("Suggestion 3");

        lblSuggestion4.setText("Suggestion 4");

        lblMeetingDescrip.setText("Description");

        taMeetingDescrip.setColumns(20);
        taMeetingDescrip.setRows(5);
        jScrollPane1.setViewportView(taMeetingDescrip);

        btnRequest.setText("Send request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMeetingname)
                    .addComponent(lblSuggestion1)
                    .addComponent(lblSuggestion2)
                    .addComponent(lblSuggestion3el4)
                    .addComponent(lblSuggestion4)
                    .addComponent(lblMeetingDescrip)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfMeetingname)
                        .addComponent(dcSuggestion1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(dcSuggestion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcSuggestion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcSuggestion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMeetingname)
                            .addComponent(tfMeetingname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuggestion1)
                            .addComponent(dcSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuggestion2)
                            .addComponent(dcSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuggestion3el4)
                            .addComponent(dcSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuggestion4)
                            .addComponent(dcSuggestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMeetingDescrip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        String meetingName = tfMeetingname.getText();
        String suggest1 = dcSuggestion1.getName();
        String suggest2 = dcSuggestion2.getName();
        String suggest3 = dcSuggestion3.getName();
        String suggest4 = dcSuggestion4.getName();
        String description = taMeetingDescrip.getText();
        
        
        try{
        String increment = Databas.getDatabas().getAutoIncrement("MOTESFORSLAG", "MF_ID");
        String sqlquery = "Insert into MOTESFORSLAG\n"
                + "values ('" + increment + "', '" + meetingName + "', '" + description + "', '" + suggest1 + "', '" + suggest2 + "', '" + suggest3 + "', '" + suggest4 + "', '" + anvID + "')";
                
        Databas.getDatabas().insert(sqlquery);
        
                JOptionPane.showMessageDialog(null, "A new suggestion has been sent!");
        }
        catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Calendar(anvID).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private com.toedter.calendar.JDateChooser dcSuggestion1;
    private com.toedter.calendar.JDateChooser dcSuggestion2;
    private com.toedter.calendar.JDateChooser dcSuggestion3;
    private com.toedter.calendar.JDateChooser dcSuggestion4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMeetingDescrip;
    private javax.swing.JLabel lblMeetingname;
    private javax.swing.JLabel lblSuggestion1;
    private javax.swing.JLabel lblSuggestion2;
    private javax.swing.JLabel lblSuggestion3el4;
    private javax.swing.JLabel lblSuggestion4;
    private javax.swing.JTextArea taMeetingDescrip;
    private javax.swing.JTextField tfMeetingname;
    // End of variables declaration//GEN-END:variables
}
