/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumextremep;

import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import oru.inf.InfException;

/**
 *
 * @author Alfred
 */
public class SkapaMote extends javax.swing.JFrame {

    String anvID;
    /**
     * Creates new form SkapaMote
     */
    public SkapaMote(String anvandarID) {
        initComponents();
        anvID = anvandarID;
        fillCbMotesForslag();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSkickaForslag = new javax.swing.JButton();
        lblMotesTitel = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        spMotesText = new javax.swing.JScrollPane();
        taMotesText = new javax.swing.JTextArea();
        lblDatumForslag = new javax.swing.JLabel();
        dcDatum = new com.toedter.calendar.JDateChooser();
        lblTidForslag = new javax.swing.JLabel();
        tfTid = new javax.swing.JTextField();
        btnSkapaMote = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        cbMotesForslag = new javax.swing.JComboBox<>();
        lblMoteSkapat = new javax.swing.JLabel();

        btnSkickaForslag.setText("Skicka förslag");
        btnSkickaForslag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkickaForslagActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMotesTitel.setText("Möte att skapa");

        lblText.setText("Text");

        taMotesText.setColumns(20);
        taMotesText.setRows(5);
        spMotesText.setViewportView(taMotesText);

        lblDatumForslag.setText("Välj datum");

        lblTidForslag.setText("Välj tid");

        tfTid.setText("t.ex 14:30");
        tfTid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTidFocusGained(evt);
            }
        });

        btnSkapaMote.setText("Skapa Möte");
        btnSkapaMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaMoteActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        cbMotesForslag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMotesForslagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTidForslag)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblText)
                                .addComponent(lblMotesTitel)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblDatumForslag))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMotesForslag, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSkapaMote, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMoteSkapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfTid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spMotesText, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotesTitel)
                            .addComponent(cbMotesForslag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumForslag, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTidForslag)
                            .addComponent(tfTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSkapaMote, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMoteSkapat))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spMotesText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(230, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTidFocusGained
        tfTid.setText("");
    }//GEN-LAST:event_tfTidFocusGained

    private void btnSkickaForslagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkickaForslagActionPerformed
        
    }//GEN-LAST:event_btnSkickaForslagActionPerformed

    
    private void btnSkapaMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaMoteActionPerformed
        
        String titel = (String)cbMotesForslag.getSelectedItem();
        String text = taMotesText.getText();
        Date datumet = dcDatum.getDate();
        String valtDatum = String.format("%1$td.%1$tm.%1$tY", datumet);
        String tiden = tfTid.getText();
        String valdTid = tiden.replaceAll("[^0-9]", "");
        
        try
        {
            String MoteIdIncrement = Databas.getDatabas().getAutoIncrement("MOTE", "M_ID");
            String sqlQueryInsertIntoMote = "Insert into mote values (" +MoteIdIncrement+ ", '" +titel+ "', '" +valtDatum+ "', '" +text+ "', " +anvID+ ", " +valdTid+ ")";
            Databas.getDatabas().insert(sqlQueryInsertIntoMote);
            
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
        
        fillCbMotesForslag();
        taMotesText.setText("");
        dcDatum = new JDateChooser();
        dcDatum.setCalendar(null);
        tfTid.setText("t.ex 14:30");
        lblMoteSkapat.setText("Möte Skapat!");
    }//GEN-LAST:event_btnSkapaMoteActionPerformed

    private void fillCbMotesForslag()
    {
        DefaultComboBoxModel cbModel = new DefaultComboBoxModel() ;
        
        String sqlFraga = "Select titel from motesforslag where a_id = " +anvID;
        try{
            ArrayList<String> motesForslag = Databas.getDatabas().fetchColumn(sqlFraga);
            for (String forslag : motesForslag) {
            cbModel.addElement(forslag);
            }
        } catch (InfException e) {
            System.out.println(e.getMessage()); 
        }
        cbMotesForslag.setModel(cbModel);
    }
    
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new Calendar(anvID).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cbMotesForslagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMotesForslagActionPerformed
        String motesForslag = (String)cbMotesForslag.getSelectedItem();
        String sqlQueryHamtaMotesForslagsText = "select text from motesforslag where titel = '" +motesForslag+ "'";
        
        try
        {
            String text = Databas.getDatabas().fetchSingle(sqlQueryHamtaMotesForslagsText);
            taMotesText.setText(text);
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_cbMotesForslagActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapaMote;
    private javax.swing.JButton btnSkickaForslag;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbMotesForslag;
    private com.toedter.calendar.JDateChooser dcDatum;
    private javax.swing.JLabel lblDatumForslag;
    private javax.swing.JLabel lblMoteSkapat;
    private javax.swing.JLabel lblMotesTitel;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTidForslag;
    private javax.swing.JScrollPane spMotesText;
    private javax.swing.JTextArea taMotesText;
    private javax.swing.JTextField tfTid;
    // End of variables declaration//GEN-END:variables
}
